clc; close all;

%%% 
% Assume the data can be generated by "DataSampling.m".
% With the data of ddot_x, dot_x and x, the estimation of the parameter
% is available.
%
% Parameter: g, angle, friction, weight
% constraint: dot_x, t
%%%
tic;
%%
% length = 0.23;

% load the data from simulink model
x_out = out.x.Data;
dot_x_out = out.dot_x.Data;
ddot_x_out = out.ddot_x.Data;
t = out.tout;

[step, numSample] = size(x_out);

% copy for later which used for data fix
x = x_out;
dot_x = dot_x_out;
ddot_x = zeros(step, numSample);

%% Check how many sample failed
% definition of "fail": can not 
numFailed = sum(x(end, :)<length);
if numFailed > 0
    disp(['ATTENTION: ', num2str(numFailed), '/', num2str(numSample), ' samples are failed.']);
    disp('The possible reason could be excessive friction or a longer required time.');
    disp('----------------------------------------------------------------------');
else
    disp(['All ', num2str(numSample), ' samples succeed.']);
    disp('----------------------------------------------------------------------');
end

%% Fix the relation between distance and velocity
% e.g. 
indexForFinalVelocity = zeros(1, numSample);

% fix the data -> consider the phsical limit
for i = 1:numSample
    temp = find(x_out(:, i)>=length, 1 );
    ddot_x(:, i) = ddot_x_out(i);
    if temp ~= 0
        indexForFinalVelocity(i) = temp;
        x(indexForFinalVelocity(i):end, i) = length;
        dot_x(indexForFinalVelocity(i):end, i) = dot_x_out(indexForFinalVelocity(i), i);
    else
        indexForFinalVelocity(i) = -1;
        x(:, i) = 0;
        dot_x(:, i) = 0;
        ddot_x(:, i) = 0;
    end
end

%% Visualization
subplot(3,1,1)
plot(t(1:max(indexForFinalVelocity)), x(1:max(indexForFinalVelocity),:));
title('distance x');
xlabel('t'); ylabel('x');
subplot(3,1,2)
plot(t(1:max(indexForFinalVelocity)), dot_x(1:max(indexForFinalVelocity),:));
title('velocity v');
xlabel('t'); ylabel('v');
subplot(3,1,3)
plot(t(1:max(indexForFinalVelocity)), ddot_x(1:max(indexForFinalVelocity),:));
title('acceleration a');
xlabel('t'); ylabel('a');

% velocity
maxVelocity = max(max(dot_x));
minVelocityIndex = find(dot_x(end, :)>0);
minVelocity = min(dot_x(end, minVelocityIndex));
% acceleration
maxAcc = max(ddot_x_out);
minAccIndex = find(ddot_x(end, :)>0);
minAcc = min(ddot_x(end, minVelocityIndex));

% min/max value analysis
disp(['In the ', num2str(numSample - numFailed), ' successful samples: '])
% velocitygu
disp(['The maximum velocity is ', num2str(maxVelocity), ' m/s.']);
disp(['The minimum velocity is ', num2str(minVelocity), ' m/s, it takes ', ...
    num2str(t(max(indexForFinalVelocity))), 's to reach the end.']);
% acceleration
disp(['The maximum acceleration is ', num2str(maxAcc), ' m^2/s.']);
disp(['The minimum acceleration is ', num2str(minAcc), ' m^2/s.']);
disp('----------------------------------------------------------------------');


toc;
